name: Run Notebooks and Store Files

on:
  push:
    branches:
      - main

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Run Notebooks
      run: |
        for notebook in $(find . -name "*.ipynb"); do
          jupyter nbconvert --to python $notebook
          python "${notebook%.*}.py"
        done

    - name: Commit and Push Files
      uses: ad-m/github-push-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        files: |
          $(find . -type f ! -name "*.ipynb" ! -name "*.py")
